import '../styles/globals.css'
import React from "react";

export const metadata = {
    title: '笔记 · 学习随记',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <section style={{boxSizing:"border-box"}}>
            {children}
        </section>
    )
}
