import type {Metadata} from 'next'
import {ConfigProvider} from "antd";
import {theme} from "@/app/config/theme";
// import AntdRegistry from "@/app/lib/AntdRegistry";
import {Providers} from "./providers";
import FloatButton from "@/app/components/FloatButton";

export const metadata: Metadata = {
    title: '学习随记',
    description: 'Generated by create next app',
}

export default function LoginLayout({
                                        children,
                                    }: {
    children: React.ReactNode
}) {
    return (
        <html lang="ch">
        <head>
            <link rel="icon"
                  href="/icons/LOGO.png"
                  type="image"
                  sizes="any"/>
        </head>
        <body>
            <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
                {children}
                {/*<FloatButton/>*/}
            </Providers>
        </body>
        </html>
    )
}
