import type {Metadata} from 'next'
import {ConfigProvider} from "antd";
import {theme} from "@/app/config/theme";
import AntdRegistry from "@/app/lib/AntdRegistry";

export const metadata: Metadata = {
    title: '学习随记',
    description: 'Generated by create next app',
}

export default function LoginLayout({
                                        children,
                                    }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <link rel="icon"
                  href="/icons/LOGO.png"
                  type="image"
                  sizes="any"/>
        </head>
        <body>
        <AntdRegistry>
            <ConfigProvider theme={theme}>
                {children}
            </ConfigProvider>
        </AntdRegistry>
        </body>
        </html>
    )
}
