import SaveHeader from "@/app/components/SaveHeader";
export const metadata = {
    title: '收藏 · 学习随记',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <SaveHeader/>
            {children}
        </>
    )
}
