import './page.scss'
import React from "react";

export const metadata = {
    title: '文档 · 学习随记',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <section>
            {children}
        </section>
    )
}
