import '../styles/globals.css'
import type {Metadata} from 'next'

export const metadata: Metadata = {
    title: '登录',
    description: 'Generated by create next app',
}

export default function LoginLayout({
                                        children,
                                    }: {
    children: React.ReactNode
}) {
    return (
        <section>
            {children}
        </section>
    )
}
