import '../../styles/globals.css'
import Header from "@/app/(Detail)/components/DetailHeader";
import {Layout} from "antd";

export const metadata = {
    title: '提交详情 · 学习随记',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <section className={'flex_column'}>
            <Header title={'提交详情'}/>
            <Layout style={{minHeight: '100%',minWidth:'100%',background:'rgb(250,250,250)', padding: 0}}>
                {children}
            </Layout>
        </section>
    )
}
