import AntdRegistry from "@/app/lib/AntdRegistry";
import {ConfigProvider} from "antd";
import {theme} from "@/app/config/theme";
import './page.scss'

export const metadata = {
    title: '知识库 · 学习随记',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <link rel="icon"
                  href="/icons/LOGO.png"
                  type="image"
                  sizes="any"/>
        </head>
        <body style={{
            margin: 0,
            padding: 0,
            width: '100%',
            height: '100%',
            overflowX: "hidden"
        }}>
        <AntdRegistry>
            <ConfigProvider theme={theme}>
                {children}
            </ConfigProvider>
        </AntdRegistry>
        </body>
        </html>
    )
}
